### ISSUE TITLE
Compiling with OS X 10.11.4 / LLVM 7.1 against Matlab R2016a

### ISSUE THREAD

**Issue by FelixLucka** [toastpp/toastpp#13]
Hi! 

I just downloaded the current version and tried to compile it on my mac (OS X 10.11.4 / LLVM 7.1, Matlab R2016a) as described in install_mac.html.
Xcode encountered the following issues (I just copied them here, is there a way to generate a niec report from it in Xcode?!):

/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.h:13:13: Typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.h:14:13: Typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:455:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:456:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:496:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')
/Users/felixlucka/Dropbox/software/toastpp-github/src/matlab2/mexutil.cc:497:12: Assigning to 'int *' from incompatible type 'size_t *' (aka 'unsigned long *')

So some type casting issue...
Thanks!

**Comment by samuelpowell** [comment]
@FelixLucka this is a known issue with Matlab changing its array indexing to 64-bit. 

Whilst we fix the problem, you can build against a previous version of MATLAB (the resultant MEX will still work on 2016a).

**Comment by samuelpowell** [comment]
@FelixLucka you can build my 64bits branch, which should work for you, see #15

**Comment by FelixLucka** [comment]
Thanks, I'll try on my mac book when I'm home tonight.

**Comment by FelixLucka** [comment]
Works like a charm, could compile without problems and toast seems to run fine. Thanks!

**Comment by samuelpowell** [comment]
@FelixLucka excellent, I'm going to reopen this issue until we merge the changes into master.
