### ISSUE TITLE
isnan ambiguity

### ISSUE THREAD

**Issue by mschweiger** [toastpp/toastpp#19]
On some gcc platforms, isnan references (in vector_imp.hpp and matrix_imp.hpp) cause compile errors due to ambiguity (after "using namespace std" both ::isnan and std::isnan are eligible).

Solve by explicitly referencing std::isnan

**Comment by samuelpowell** [comment]
Fixed in ece8bd0

**Comment by mschweiger** [comment]
MSVC2008 doesn't implement std::isnan, so this needs to be defined in arch.h

**Comment by mschweiger** [comment]
fixed with #30
