### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by mschweiger** [toastpp/toastpp#27]
Is there a way to replicate the binary release packages I used to have on sourceforge?

I notice that there is currently one "Release" from 2014, which was presumably converted from an SVN tag. It only contains source packages. Does github allow to create binary distribution packages (maybe with the help of the CI server)? We would need separate packages for Linux, Mac and Windows.

If that is not easy to set up, an alternative might be to build the binary packages manually, upload them to a UCL server, and link to them from a Wiki page.

**Comment by samuelpowell** [comment]
Yes, the process is quite straightforward:
- create a tag, say v2.0.0, which refers to the state of master at that time (this can be done through the web interface)
- check out the tag (which is like a branch which doesn't change) and build the binaries
- create a release and add release notes on the GitHub, then upload the binaries (there's a box that lets you do this when you create the release)

Have a look here for an example of what it looks like when its all done: https://github.com/JuliaLang/julia/releases.

In the future we could get the CI servers to generate binaries, but I'm not sure I know enough to get that working this time around (especially as we are still to set up the Windows CI).

We should probably prepare a release immediately, as you noted in #23. The only thing that needs to be done to make master releasable is to add asserts in the OS X code branch of the OpenGL projection code that prevents execution. We can note this limitation in the release notes. Are you able to add these?

**Comment by samuelpowell** [comment]
@mschweiger I have created PR #29 to prevent segfaults when trying to use OpenGL cameras on OS X. Once merged I think it would be good to merge the documentation updates, then tag for release. Note that we can edit releases after they're created so that I can add binaries independently.

**Comment by mschweiger** [comment]
@samuelpowell You probably saw that I have now created the v2.0.1 source release. I've added the precompiled Linux package, and will do the Windows package next. I'll leave the Mac package to you whenever you find time.
Since the source package now takes the role of the previous "common" package, some of the installation documentation probably needs to be updated.
I'll also try to install Toast from the release to make sure everything works.

**Comment by samuelpowell** [comment]
@mschweiger  ~~I'll wait until #30 passes CI, we can then merge, update the release to tag v2.0.2, and I'll build and upload binaries. Is that a good plan?~~ 

How do you want to deal with the release and #30?

**Comment by samuelpowell** [comment]
@mschweiger I've uploaded binaries for v2.0.1. Let me know how you want to handle #30 w.r.t. the Windows build. I guess we need a v2.0.2 bugfix release!

**Comment by mschweiger** [comment]
@samuelpowell Yes, unfortunately I had to open #30 in order to get the Windows version to compile. So strictly speaking the Windows version is now not exactly v2.0.1. Clearly I shouldn't have tagged the release before making sure that all target platforms compile. You live and learn ...
I agree we should have a 2.0.2. release soon to fix the inconsistencies.
I'll also try to get the Windows build pipeline sorted out so we can put the Windows build into CI. Unfortunately, I've been building with VS2008 so far, and the msbuild command only seems to be available since VS2010. I am currently migrating to a later VS version.

**Comment by samuelpowell** [comment]
@mschweiger Okay, I will branch to release-v2.0.2, and build from there. We can then tag on that branch which means we can still push new things onto master without changing anything. I will open an issue accordingly.

Keep me up to date on the msbuild stuff.
