### ISSUE TITLE
Release v2.0.2

### ISSUE THREAD

**Issue by samuelpowell** [toastpp/toastpp#31]
Draft release opened targeting the release-v2.0 branch, close when binaries uploaded and release finalised.

**Comment by samuelpowell** [comment]
@mschweiger I've pulled in your recent changes to release-2.0 branch, given changes to projector functions, etc., is now a good time to do v2.0.2?

**Comment by samuelpowell** [comment]
@mschweiger I have updated the build configuration for macOS, built, tested and uploaded binaries to the draft release. Can you do the same for Windows/Linux, then we can issue the release.

**Comment by mschweiger** [comment]
@samuelpowell Ok done. The binary packages for Linux and Windows are now uploaded.

**Comment by samuelpowell** [comment]
v2.0.2 released!
