### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by mschweiger** [toastpp/toastpp#38]
Something odd has happened to the file permissions on my local repository. All files now seem to have permissions 777 (rwx for owner, group and world). I suspect that this may have happened when I committed from Windows at some stage (Windows doesn't seem to uderstand linux permissions). My local repository is stored on an NTFS partition, so I can access it from both Linux and Windows. That in itself shouldn't be a problem - Linux can keep track of permissions on NTFS, but apparently writing to the repository from Windows destroys it.

Strangely, when I clone the repository on a Linux file system, the permissions change. Some files now have permission 664 (i.e. non-executable). It looks like git is trying to guess reasonable permissions. It fails for numerics/Mesa-7.5.1/configure, which is now no longer executable and breaks the build.

**Comment by samuelpowell** [comment]
@mschweiger is this fixed by #39 ?

**Comment by mschweiger** [comment]
Yes, this appears to be fixed now in master. I cloned it into a Linux partition to check, and the permissions look ok now.
Fixed by #39.
