### ISSUE TITLE
Matlab 2015b UI issue

### ISSUE THREAD

**Issue by andreafarina** [toastpp/toastpp#41]
Dear Toast stuff I would like to report a strange behaviour I see during toast installation.
**Compiler settings**: gcc-4.7,g++-4.7,gfortran-4.7 and --enable-threads --enable-fdot
**Scenario 1**: /usr/local/bin/mex linked to MatlabR2015b and Matlab compiler set also to 4.7.
1. Under _Matlab-R2015b_ the function MakeProjectorLists causes a crash with Segmentation fault (core dumped). 
2. By lunching matlab with -nodesktop flag the error disappears but you loose the GUI. 
4. By connecting with vnc to the machine with the installation, the problem disappears also with Matlab GUI.
3. The function toastThreadCounts returns 1 (it should return 40).

**Scenario 2**: /usr/local/bin/mex linked to MatlabR2013b and Matlab compiler set also to 4.7.
1. Under _Matlab-R2013b_ all works smoothly both directly on the machine and remotely.
2. The function toastThreadCounts returns correctly 40.

**Scenario 3**: /usr/local/bin/mex linked to MatlabR2013b and Matlab compiler set also to 4.7.
1. Under _Matlab-R2015b_  the error is the same of Scenario 1.
2. The function toastThreadCounts returns correctly 40.

**Comment by samuelpowell** [comment]
@mschweiger any ideas about this?

**Comment by mschweiger** [comment]
It looks like the TOAST_THREAD flag is not carried over into the Matlab build. Working on it ...

**Comment by samuelpowell** [comment]
Are there any reasons not always to be multi-threaded?

**Comment by mschweiger** [comment]
Well, at least for testing/debugging it's good to be able to disable threads. Although maybe we should make multithreaded build the default for configure (change --enable-threads to --disable-threads).

**Comment by samuelpowell** [comment]
Ah yes, good point.

**Comment by samuelpowell** [comment]
Is changing it to --disable-threads simply a configure time change? That is to say, you're not intending to invert the pre-processor logic?

If so, is it worth changing fdot also? After all, we now support this on all systems, correct?

**Comment by mschweiger** [comment]
Yes, this should only affect the configure script, not the Makefiles or anything further downstream.

Regarding the fdot flag, this needs a bit more work as it is currently also entangled with the Mesa support. It should be split into fdot support (enabled by default) and Mesa support (disabled by default).

**Comment by samuelpowell** [comment]
Understood

**Comment by mschweiger** [comment]
@andreafarina Can you please check if the crash with MakeProjectorLists still occurs with the lastest 2.0.2 release (or current master branch)? We have now implemented a version of this function that doesn't require Mesa, and which should fix related problems.

Can you also check if the 41-matlab-threads branch fixes the problem with toastThreadCount returning 1 regardless of available cores?

**Comment by andreafarina** [comment]
@mschweiger I've compiled (remotely using vnc) the new version two times from scratch: 1) using --enable-fdot --enable-threads, 2) using --enable-fdot.  For both I've used gcc 4.9.4 and Matlab 2016b. For both cases toastThreadCount returns 1 and the projection function was very very slow. 
Can you tell me your configuration in term of gcc,g++,gfortrtan version, Matlab version and mex command version?
Tomorrow I'll try to run it directly on the server to check if the MakePRojectionList gives segmentation fault.

A question: using --enable-fdot is MESA still supported or no? Is the slowness of the projection function due to the disabled MESA support?
Thanks

**Comment by mschweiger** [comment]
> For both cases toastThreadCount returns 1

This is expected for the master branch, but it shouldn't happen for the "41-matlab-threads" branch. Do you still get the same result with the 41-matlab-threads branch?

> and the projection function was very very slow

This indicates that non-Mesa (non-accelerated version) of the projector function is used. Note that there is now an additional optional 'driver' parameter to toastMakeProjectorList:

`toastMakeProjectorList ( ... , 'driver', 'mesagl')`

This will use the accelerated Mesa driver, which is only available if toast was compiled with "--enable-fdot", which yours is. The default software driver is a fallback option for when Mesa support was not compiled in.

**Comment by andreafarina** [comment]
Thank you martin,
I'm not used to GitHub and so I've compiled the master branch! Now I've downloaded the 41-matlab-threads and I'll check as soon as possible.
Thanks again
Andrea

**Comment by andreafarina** [comment]
Hi Martin, Iv'e tried the branch and it works smoothly under Matlab 2016b with gcc4.9. Threads are correctly recognised now! Tomorrow I'll try directly on the Dell machine without vnc and I'll tell you about the segmentation fault.

**Comment by andreafarina** [comment]
Hi Martin, I think I've got the point about the issue occurring when I lunch the Projection function (with MESA) directly on the machine and/or using VNC. 
The key is a Matlab starting option "matlab -softwareopengl". Before the splash screen you see a line: "MATLAB is selecting SOFTWARE OPENGL rendering". If you run Matlab with this option the Projection works smoothly. 
I don't know why, but if you lunch Matlab remotely using vnc this option is used by default and you don't need to put it in the command line, but if you run Matlab directly on the machine it isn't and consequently you have to force the option "-softwareopengl" in the command line. May be that exploring default options it is possible to make this as default when Matlab is run directly on the machine, but I don't know.
(Matlab R2016b, gcc,g++,gfortran: 4.9.4, Ubuntu 14.04 LTS)

**Comment by mschweiger** [comment]
Ah ok, interesting. This could indicate that there is some conflict between Matlab's version of the Mesa libraries and the ones used by Toast. I'll try to test that. Unfortunately, my usual Linux build machine has a crappy graphics card, so Matlab automatically always switches to software rendering. I'll have to find a machine that doesn't.

**Comment by samuelpowell** [comment]
@andreafarina just to confirm, the `41-matlab-threads branch` fixes the threading issue?

**Comment by andreafarina** [comment]
@samuelpowell yes Sam for me it is fixed.

**Comment by samuelpowell** [comment]
@andreafarina okay, please open a new issue for the OpenGL problems so we can track it separately
