### ISSUE TITLE
Git LFS

### ISSUE THREAD

**Issue by samuelpowell** [toastpp/toastpp#52]
@mschweiger we are currently exceeding the free GitHub LFS download quota, which will cause CI to fail, amongst other things, until the next billing cycle.

The storage and bandwidth usage is dominated by two files in `examples/matlab/gmsh`, can we remove these and/or host them externally?

**Comment by mschweiger** [comment]
I've committed a branch that has those files removed, but is that enough? I guess the files will remain in the repository and so count towards the storage quota. If the problem was bandwidth, this may fix it, but if it was storage, then we may have to edit the repository to delete the files.

**Comment by samuelpowell** [comment]
Sadly not - every git repository, local or remote, contains a full history. We have to rewrite the history to fix this. I can do this, but it will break open PRs. I propose the following
1. I'll pay for more storage and bandwidth to restore CI and our ability to clone, etc.
2. We review and merge or close all open PRs
3. I'll rewrite the history and merge
4. Release 2.0.2

What do you think?

**Comment by mschweiger** [comment]
Sounds like a good plan.

**Comment by samuelpowell** [comment]
Files removed and history rewritten to purge
